//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Id_account { get; set; }
        public int Fk_employee { get; set; }
        public int Fk_user { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual User User { get; set; }
    }
}
