//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_dispensed_computers
    {
        public int Id_history_dispensed_computer { get; set; }
        public int Number_dispensing { get; set; }
        public string Operation { get; set; }
        public int Computer { get; set; }
        public System.DateTime CreateAt { get; set; }
    }
}
