//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_dispensed_peripherals
    {
        public int Id_list_dispensed_peripheral { get; set; }
        public int Fk_number_dispensing { get; set; }
        public int Fk_peripheral { get; set; }
    
        public virtual Dispensing_peripherals Dispensing_peripherals { get; set; }
        public virtual Peripheral Peripheral { get; set; }
    }
}
