//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peripheral
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Peripheral()
        {
            this.List_dispensed_peripherals = new HashSet<List_dispensed_peripherals>();
        }
    
        public int Id_peripheral { get; set; }
        public int Fk_type_peripheral { get; set; }
        public int Fk_manufacturer { get; set; }
        public string Name { get; set; }
        public int Inventory_number { get; set; }
        public int Fk_status_equipment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<List_dispensed_peripherals> List_dispensed_peripherals { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Statuses_equipment Statuses_equipment { get; set; }
        public virtual Types_peripherals Types_peripherals { get; set; }
    }
}
