//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Model
{
    using System.Collections.Generic;

    using DevExpress.Mvvm;

    public partial class Posts_employees:BindableBase
    {
        public Posts_employees()
        {
            using var db = new InventoryEntities();
        }

        public int Id_post_employee { get; set; }
        public int Fk_employee { get; set; }
        public int Fk_post { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Post Post { get; set; }
    }
}
