//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Model
{
    using System.Collections.Generic;
    using System.Collections.ObjectModel;

    using DevExpress.Mvvm;

    public partial class Post : BindableBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.Posts_employees = new HashSet<Posts_employees>();
        }
    
        public int Id_post { get; set; }
        public string Name { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Posts_employees> Posts_employees { get; set; }

        public static void AddPost(string name)
        {
            using var db = new InventoryEntities();

            var post = new Post
            {
                Name = name
            };

            db.Posts.Add(post);
            db.SaveChanges();
        }
    }
}
