//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Model
{
    using System;
    using System.Collections.Generic;

    using DevExpress.Mvvm;

    public partial class Processors_in_computers : BindableBase
    {
        public int Id_processor_in_computer { get; set; }
        public int Fk_inventory_number_processor { get; set; }
        public int Fk_computer { get; set; }
    
        public virtual Computer Computer { get; set; }
        public virtual Inventory_numbers_processors Inventory_numbers_processors { get; set; }
    }
}
