//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Model
{
    using System;
    using System.Collections.Generic;

    using DevExpress.Mvvm;

    public partial class Processor : BindableBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Processor()
        {
            this.Inventory_numbers_processors = new HashSet<Inventory_numbers_processors>();
        }
    
        public int Id_processor { get; set; }
        public int Fk_manufacturer { get; set; }
        public string Name { get; set; }
        public int Fk_socket { get; set; }
        public Nullable<int> Amount_cores { get; set; }
        public Nullable<double> Base_frequency { get; set; }
        public Nullable<int> Fk_unit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_numbers_processors> Inventory_numbers_processors { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Socket Socket { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
