//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ram
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ram()
        {
            this.Inventory_numbers_ram = new HashSet<Inventory_numbers_ram>();
        }
    
        public int Id_ram { get; set; }
        public int Fk_manufacturer { get; set; }
        public string Name { get; set; }
        public int Fk_type_memory { get; set; }
        public double Memory_size { get; set; }
        public Nullable<double> Clock_frequency { get; set; }
        public Nullable<int> Fk_unit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_numbers_ram> Inventory_numbers_ram { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Types_memory Types_memory { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
