//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Model
{
    using System;
    using System.Collections.Generic;

    using DevExpress.Mvvm;

    public partial class Roles_users : BindableBase
    {
        public int Id_role_user { get; set; }
        public int Fk_user { get; set; }
        public int Fk_role { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
    }
}
