//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Model
{
    using System;
    using System.Collections.Generic;

    using DevExpress.Mvvm;

    public partial class Ssd : BindableBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ssd()
        {
            this.Inventory_numbers_ssd = new HashSet<Inventory_numbers_ssd>();
        }
    
        public int Id_ssd { get; set; }
        public int Fk_manufacturer { get; set; }
        public string Name { get; set; }
        public int Fk_type_ssd { get; set; }
        public double Memory_size { get; set; }
        public int Fk_unit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_numbers_ssd> Inventory_numbers_ssd { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Types_ssd Types_ssd { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
